# Generated by Django 3.2.8 on 2024-06-16 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
